# Generated by Django 4.0.6 on 2022-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nd', models.CharField(max_length=10, verbose_name='nd')),
                ('bonus_ataque', models.IntegerField(verbose_name='bonus_ataque')),
                ('dano_medio', models.IntegerField(verbose_name='dano_medio')),
                ('defesa', models.IntegerField(verbose_name='defesa')),
                ('resis_forte', models.IntegerField(verbose_name='resis_forte')),
                ('resis_media', models.IntegerField(verbose_name='resis_media')),
                ('resis_fraca', models.IntegerField(verbose_name='resis_fraca')),
                ('pv', models.IntegerField(verbose_name='pv')),
                ('cd', models.IntegerField(verbose_name='cd')),
            ],
        ),
    ]
