# Generated by Django 4.0.6 on 2022-07-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ameacas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poderes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_poder', models.CharField(max_length=50, verbose_name='nome_poder')),
                ('descricao_poder', models.TextField(verbose_name='descricao_poder')),
            ],
        ),
    ]
