# Generated by Django 4.0.6 on 2022-07-21 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ameacas', '0002_poderes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poderes',
            name='descricao_poder',
        ),
        migrations.AlterField(
            model_name='poderes',
            name='nome_poder',
            field=models.CharField(max_length=100, verbose_name='nome_poder'),
        ),
    ]
